apiVersion: v1
kind: Pod
metadata:
  name: hello-python
spec:
  nodeName: ip-172-31-53-218.us-west-2.compute.internal
  containers:
  - name: test
    image: public.ecr.aws/d1x6q6g5/myecr
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
